{
 "title": "Dougs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Histogram",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "http_requests_total{path!=\"/metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Req 200 Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "http_requests_total{status_code=\"200\",path!=\"/metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total req with 500 & 404 code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "http_requests_total{status_code=~\"500|404\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod restart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/example process time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_gauge_example{method=\"GET\",status=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "http_request_duration_summary_seconds{quantile=~\"0.5|0.9|0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}